import { useEffect, useState } from "react";
import type { AdminBackupsAdapter, AdminOperationalStatus, AdminSettingsAdapter, AdminSettingField } from "../core";
import { AdminPanelStateView } from "./AdminPanelState";

export function AdminStatusSummary({ items }: { items: readonly AdminOperationalStatus[] }) { return <dl className="admin-kit__status-summary">{items.map(item => <div className={`admin-kit__status admin-kit__status--${item.tone ?? "neutral"}`} key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd>{item.detail ? <small>{item.detail}</small> : null}</div>)}</dl>; }

export function BackupsPanel({ adapter, title = "Backups" }: { adapter: AdminBackupsAdapter; title?: string }) {
 const [items,setItems]=useState<readonly import("../core").AdminBackupSummary[]>(); const [error,setError]=useState<string>(); const [busy,setBusy]=useState(false);
 const load=async()=>{try{setItems((await adapter.list({page:1,pageSize:25})).items)}catch(e){setError(e instanceof Error?e.message:"Unable to load backups.")}}; useEffect(()=>{void load()},[adapter]);
 if(error&&!items)return <AdminPanelStateView state={{kind:"error",detail:error,onRetry:()=>void load()}}/>; if(!items)return <AdminPanelStateView state={{kind:"loading",label:"Loading backups…"}}/>;
 return <section className="admin-kit__operations" aria-label={title}><header><div><h2>{title}</h2><p>{items.length} recent recovery points</p></div>{adapter.run?<button disabled={busy} onClick={()=>void (async()=>{setBusy(true);try{await adapter.run!.execute();await load()}finally{setBusy(false)}})()}>Run backup</button>:null}</header>{error?<AdminPanelStateView state={{kind:"error",detail:error,onRetry:()=>void load()}}/>:null}<div className="admin-kit__operations-table-wrap"><table><thead><tr><th>Backup</th><th>Created</th><th>Size</th><th>Status</th><th /></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.label}</strong>{item.detail?<small>{item.detail}</small>:null}</td><td>{item.createdAt}</td><td>{item.size??"—"}</td><td><span className={`admin-kit__state-pill admin-kit__state-pill--${item.state}`}>{item.state}</span></td><td>{adapter.restore?<button disabled={busy||item.state!=="completed"} onClick={()=>void adapter.restore!.execute({backupId:item.id})}>Restore</button>:null}</td></tr>)}</tbody></table></div></section>;
}

export function SettingsPanel({ adapter, title = "Settings" }: { adapter: AdminSettingsAdapter; title?: string }) { const [fields,setFields]=useState<readonly AdminSettingField[]>(); const [values,setValues]=useState<Record<string,string|boolean>>({}); const [saving,setSaving]=useState(false); const [error,setError]=useState<string>(); useEffect(()=>{void adapter.load().then(next=>{setFields(next);setValues(Object.fromEntries(next.map(x=>[x.id,x.value])))}).catch(e=>setError(e instanceof Error?e.message:"Unable to load settings."))},[adapter]); if(error&&!fields)return <AdminPanelStateView state={{kind:"error",detail:error}}/>; if(!fields)return <AdminPanelStateView state={{kind:"loading",label:"Loading settings…"}}/>; return <form className="admin-kit__settings" aria-label={title} onSubmit={e=>{e.preventDefault();void (async()=>{setSaving(true);setError(undefined);try{await adapter.save.execute({values})}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save settings.")}finally{setSaving(false)}})()}}><header><div><h2>{title}</h2><p>Changes are applied when saved.</p></div><button disabled={saving}>Save changes</button></header>{error?<AdminPanelStateView state={{kind:"error",detail:error}}/>:null}{fields.map(field=><label key={field.id}><span>{field.label}</span>{field.description?<small>{field.description}</small>:null}{field.type==="boolean"?<input type="checkbox" checked={Boolean(values[field.id])} onChange={e=>setValues(v=>({...v,[field.id]:e.target.checked}))}/>:<input type={field.sensitive?"password":"text"} value={String(values[field.id]??"")} onChange={e=>setValues(v=>({...v,[field.id]:e.target.value}))}/>}</label>)}</form>; }
